### ISSUE TITLE
R2RMLTC0018a: padding of CHAR columns in MySQL

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/r2rml-test-cases-support#10]
MySQL allots the number of characters for values, but silently removes them when retrieving values. This can be disabled by enabling `PAD_CHAR_TO_FULL_LENGTH` in the docker image. However, this is soon to be deprecated. May this have an impact on the results? 

`SET SESSION sql_mode = 'PAD_CHAR_TO_FULL_LENGTH';` 

This appears not to be the case for PostgreSQL (according to their documentation).

**Comment by dachafra** [comment]
Could you make a PR with the update?

**Comment by chrdebru** [comment]
Ok! This was an easy fix, but PAD_CHAR_TO_FULL_LENGTH will be removed from MySQL in the near future. We need to bear in mind that the tests do not test a database's compliance with ANSI SQL instead of a mapping engine's compliance with R2RML, though.

**Comment by DylanVanAssche** [comment]
MySQL doesn't comply then with ANSI SQL here, shouldn't we just drop the test for MySQL and mark it as 'not applicable' to MySQL?
This isn't a R2RML problem, but a RDB problem, I agree.

**Comment by chrdebru** [comment]
That could be an elegant solution, yes. This could then also be used for [Issue 7](https://github.com/kg-construct/r2rml-test-cases-support/issues/7) where MySQL uses delimited and regular identifiers interchangeably.

**Comment by DylanVanAssche** [comment]
> That could be an elegant solution, yes. This could then also be used for [Issue 7](https://github.com/kg-construct/r2rml-test-cases-support/issues/7) where MySQL uses delimited and regular identifiers interchangeably.

Indeed, as the `rr:sqlVersion: rr:SQL2008` is, the RDB engines must comply with that spec, if they don't the test doesn't apply.
If we have something like `rr:MySQL<VERSION>` in the future, another set of test cases for MySQL could be introduced which follow the MySQL dialect, same for other RDBs

**Comment by dachafra** [comment]
I will say that we should close this issue and open a new one with the correct problem (marking not applicable to MySQL in this cases)

**Comment by DylanVanAssche** [comment]
@dachafra Agreed :) @chrdebru Will you open one? You are more aware of this for having a nice issue description.
