### ISSUE TITLE
#R2RMLTC0016c: timezone of docker instance UTC

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/r2rml-test-cases-support#13]
Docker instance for mysql stores values as UTC. Retrieving the values takes into account the timezone difference resulting in the actual output be a number of hours of. One can change this by appending the following information for the database connection. E.g., by appending `?useLegacyDatetimeCode=false&serverTimezone=Europe/Brussels` (for me, that is) in the JDBC connection URL. Shouldn't we document this on the README? Another option is the ensure that the docker instance uses the host's timezone, but I haven't found a way to do that yet.

**Comment by dachafra** [comment]
IMO this is a problem of the connection between the engine and the database and should be solved in the configuration of the first one. We could add a note in the README.

**Comment by chrdebru** [comment]
Done. This can be closed if the note looks good (enough).
