### ISSUE TITLE
R2RMLTC0016b: REAL type has no standardized precision.

### ISSUE THREAD

**Issue by mcndt** [kg-construct/r2rml-test-cases-support#18]
Test case R2RMLTC0016b fails for PostgreSQL because in postgres the[ `REAL` type means single-precision floating point](https://www.postgresql.org/docs/13/datatype-numeric.html), whereas the [expected output](https://github.com/kg-construct/r2rml-test-cases-support/blob/main/R2RMLTC0016b/mappedb.nq) assumes the decimal-to-float conversion in the SQL script used double-precision.

The result is a comparison failure:
- Expected: `...<http://example.com/weight> "7.022E1"...`
- Actual: `...<http://example.com/weight> "7.0220001E1"...`

A solution could be to use the `FLOAT(p)` notation to explicitly require a certain precision. This should hopefully be enforced the same in both RDBs.

**Comment by mcndt** [comment]
After some additional investigation:
- The test passes using the script provided in this repo. The tests in this repo are run using Postgres 13. 
- The same test fails using a Postgres 10.4 container (which is the version I used when I initially discovered this problem)

Unfortunately the Postgres team did not update their documentation to reflect the change in meaning of the `REAL` type. I also don't know at which version the change happened

**Comment by dachafra** [comment]
To-Do: Add in the README which versions of the RDBMS are used for running the test-cases.
This is not an actual bug, but a good question.
