### ISSUE TITLE
Misleading test

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/r2rml-test-cases-support#5]
In test R2RMLTC0002a, you are testing the use of two columns in a IRI. The test case also assumes that datatype conversions are correct (test R2RMLTC0016a). With a mistake there, the test fails even when the IRI generated is correct. Maybe use constants for a predicate and an object to do this test?

**Comment by pheyvaer** [comment]
Yeah good remark. Maybe we can even skip the Predicate Object Maps all together? Then we only have the class triples.

**Comment by dachafra** [comment]
I would be more in favor of removing the xsd:integer datatype from the [generated triple ](https://github.com/kg-construct/r2rml-test-cases-support/blob/main/R2RMLTC0002a/mappeda.nq#L2) and not making many modifications in the test-case

**Comment by chrdebru** [comment]
If no rr:datatype is provided, then the datatype depends on the nature of the column (cfr. R2RML spec). So removing the xsd:integer field in the generated will result in graphs that are different.

**Comment by chrdebru** [comment]
There are a couple of other tests that "suffer" from this issue (e.g., R2RMLTC0009d). It would be good to go over each of these mappings and ensure that the test is minimal enough.

**Comment by dachafra** [comment]
> There are a couple of other tests that "suffer" from this issue (e.g., R2RMLTC0009d). It would be good to go over each of these mappings and ensure that the test is minimal enough.

100% agree

**Comment by dachafra** [comment]
As we have recently discussed, I would suggest to not modify this test-case but taking into account these issues during the creation of the atomic test-cases.  What do you think? @chrdebru

**Comment by chrdebru** [comment]
I agree. This one should remain. But a good exercise would be to revise the R2RML cases and render those more atomic. We all know R2RML, and having those foundations right from the start will help us for the other test cases. What do you think?

**Comment by dachafra** [comment]
Totally agree, I and @jatoledo will prepare an initial analysis of the R2RML test-cases and give an overview during the next meeting

**Comment by dachafra** [comment]
We will start in this spreadsheet: https://docs.google.com/spreadsheets/d/1zVHwSpzzhLWZCX5T75HP-7EW7DLnNKN7mJYsiX9s8yg/edit#gid=990981462

**Comment by DylanVanAssche** [comment]
> I agree. This one should remain. But a good exercise would be to revise the R2RML cases and render those more atomic. We all know R2RML, and having those foundations right from the start will help us for the other test cases. What do you think?

What about 'R2RML Test Cases 1.1' or 'Revised R2RML Test Cases'?
This way we keep the original test cases as they are now and publish the revised set against which we test.

**Comment by dachafra** [comment]
yes, I liked the idea!
