### ISSUE TITLE
R2RMLTC0020a: base IRI assumed to be declared in the mapping

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/r2rml-test-cases-support#9]
The test assumes that the base-IRI is declared in the mapping. The specification does state: "An R2RML data validator is a system that takes as its input an R2RML mapping, a base IRI, and a SQL connection to an input database, and checks for the presence of data errors. [...]." The base IRI is thus an input variable and not necessarily part of the mapping. Tools such as db2triples, ontop, and r2rml-f take as input the base-IRI. The base-IRI _for_ a mapping should not be conflated with the base-IRI _of_ a mapping.

**Comment by chrdebru** [comment]
This issue also arises in other tests.

**Comment by chrdebru** [comment]
The original test cases state that:

> Throughout all test cases, we use the base IRI <http://example.com/base/>:
> - to turn relative IRIs generated by the Direct Mapping into absolute IRIs,
> - as the required base IRI input to the R2RML processor.

So it could be a matter of documenting that the base IRI has to be provided as an input (e.g., via a config file or command line).

**Comment by dachafra** [comment]
Reviewing the mappings from R2RML test-cases, I saw that all of them add the `@base <http://example.com/base/> ` at the begging, I assume that this base IRI is for the mapping, and another one should be provided as an input for data generation, right?

**Comment by chrdebru** [comment]
Yes. As the original R2RML spec did specify it is given as input. Mappings having their own base IRI also makes sense for governance and provenance purposes. R2RML-F "failed" on these tests as it assumed no base IRI was passed as an extra argument, this was easily solved by adding the flag. So this implementation of the test wrongly assumed that the base IRI of the mapping was the same. 

1. This issue is easily solved by stating, in the documentation, that a base IRI is assumed to be passed as an extra argument (whether it is used or not). 
2. It would be even better if the base IRI of the mappings and that of the generated resources is also explicitly different to avoid confusion in the future. 

I can have a go at (1), but we should consider (2) for the new version of the test cases.

**Comment by dachafra** [comment]
Indeed, this also affects https://github.com/kg-construct/rml-test-cases and https://github.com/kg-construct/rml-test-cases
I agree with you, I would go for (1) in this case and consider (2) for the next generation.

So, the question is what happens to engines when they do not provide the base IRI and they take the one defined in the mapping? The test-case output will be valid but the execution won't. Something out-of-the-scope from this, IMO, but better to clarify
